### ISSUE TITLE
Null Safety support 

### ISSUE THREAD

**Issue by medyas** [Fliggy-Mobile/fdottedline#3]
could you add support for null safety ?

**Comment by ygorcf** [comment]
Add support please

**Comment by dreamfly32** [comment]
kpi of king

**Comment by vukhacbiet** [comment]
Please tell me any updates?

**Comment by Amir-P** [comment]
For now you can add this to your `pubspec.yaml`:

```YAML
fdottedline:
  git:
    url: https://github.com/Taskulu/fdottedline.git
    ref: null-safety
```
