### ISSUE TITLE
Sometimes not loading

### ISSUE THREAD

**Issue by Karthick47v2** [Fliggy-Mobile/fdottedline#5]
I am wrapping this around an image. It's only working as intended for half of the time.  It doesn't even load fully even if I wait for 5-6 mins.

I am using `fdottedline: ^1.0.1`
<p>
<img src="https://user-images.githubusercontent.com/63592766/169199581-3023687f-4b2e-4bb3-acae-0b15c6607104.png" alt="ss" height=500/>
<img src="https://user-images.githubusercontent.com/63592766/169199791-336cbf9e-7b14-4e74-a3b3-a6012f4c561d.png" alt="ss1" height=500/>
</p>

**Comment by Karthick47v2** [comment]
Problem is fdottedline doesn't wait until image gets loaded. So It won't render. I got that small circle on 2nd pic, as I wrapped image with container which had margin (so fdottedline rendered around it).

Since this repo is not active, if anyone having same problem, you can add this to your `pubspec.yaml`

```
dependencies:
  fdottedline:
    git:
      url: https://github.com/Karthick47v2/fdottedline.git
      ref: img-fix
```
https://github.com/Karthick47v2/fdottedline/tree/img-fix
And I also updated with null safety
